# Server
server.port=8080

# PostgreSQL (Supabase - Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.xlvgipyrkkgdkgfhkcku
spring.datasource.password=K@LuT3ch247
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Date format
spring.mvc.format.date=yyyy-MM-dd

# Disable jsessionid in URL (use cookies only)
server.servlet.session.tracking-modes=cookie
